#!/bin/sh
r=0x$(expr substr "$1" 1 2)
g=0x$(expr substr "$1" 3 2)
b=0x$(expr substr "$1" 5 2)
printf '\033[38;5;%sm' "$((
    ( ($r + 25) * 5 / 255) * 36 +
    ( ($g + 25) * 5 / 255) *  6 +
    ( ($b + 25) * 5 / 255)      +
    16
))"
